---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vishnu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vishnu
  template:
    metadata:
      labels:
        app: vishnu
    spec:
      containers:
      - name: vishnu
        image: vishnu0728/docker-project
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: vishnu-service
spec:
  selector:
    app: vishnu
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
